# Generated by Django 5.0.6 on 2024-09-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfitting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usregister',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
