# Generated by Django 5.0.6 on 2024-10-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfitting', '0002_alter_usregister_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usregister',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
