# Generated by Django 5.0.2 on 2024-12-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfitting', '0005_alter_shopowner_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopowner',
            old_name='name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shopowner',
            old_name='image',
            new_name='shopimage',
        ),
        migrations.AddField(
            model_name='shopowner',
            name='age',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='licenceno',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='place',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='shopaddress',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='shopid',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='shopname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='shopownername',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
