# Generated by Django 4.2.16 on 2024-12-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfitting', '0006_rename_name_shopowner_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='addproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField(blank=True, max_length=10, null=True)),
                ('productname', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(choices=[('tshirt', 'T-shirt'), ('shirt', 'Shirt'), ('shoes', 'Shoes'), ('westernwear', 'Westernwear')], max_length=20)),
                ('price', models.IntegerField(blank=True, max_length=10, null=True)),
                ('size', models.IntegerField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('shopimage', models.ImageField(blank=True, null=True, upload_to='shop/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shopowner',
            name='age',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
