# Generated by Django 4.2.16 on 2024-12-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfitting', '0007_addproduct_alter_shopowner_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='productid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
