# Generated by Django 4.2.16 on 2024-12-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfitting', '0009_remove_addproduct_productid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct',
            old_name='shopimage',
            new_name='image',
        ),
    ]
