# Generated by Django 5.1.4 on 2024-12-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfitting', '0010_rename_shopimage_addproduct_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('Feedback', models.TextField()),
                ('rating', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
