# Generated by Django 5.1.4 on 2024-12-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfitting', '0011_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Feedback',
            new_name='feedback',
        ),
    ]
