# Generated by Django 5.1.4 on 2024-12-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfitting', '0013_addproduct_product_id_addproduct_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usregister',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
