# Generated by Django 5.1.4 on 2025-01-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfitting', '0015_addproduct_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_success',
            field=models.BooleanField(default=False),
        ),
    ]
