# Generated by Django 5.0.4 on 2025-01-13 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfitting', '0017_fileupload_remove_transaction_payment_success_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='virtualfitting.transaction'),
            preserve_default=False,
        ),
    ]
