# Generated by Django 5.0.4 on 2025-01-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfitting', '0018_feedback_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='category',
            field=models.CharField(choices=[('tshirt', 'T-shirt'), ('shirt', 'Shirt'), ('shoes', 'Shoes'), ('westernwear', 'Westernwear'), ('watch', 'Watch'), ('glass', 'Glass'), ('cap', 'Cap')], max_length=20),
        ),
    ]
