# Generated by Django 5.1.4 on 2025-01-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfitting', '0019_alter_addproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='category',
            field=models.CharField(choices=[('tshirt', 'T-shirt'), ('shirt', 'Shirt'), ('shoes', 'Shoes'), ('westernwear', 'Westernwear'), ('watch', 'Watch'), ('glass', 'Glass'), ('cap', 'Cap'), ('casualwear', 'Casualwear'), ('jewellery', 'Jewellery'), ('coat', 'Coat'), ('gown', 'Gown')], max_length=20),
        ),
    ]
