# Generated by Django 5.1.4 on 2025-01-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualfitting', '0020_addproduct_gender_alter_addproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
